In [39]:
import numpy as np
from sklearn.cluster import KMeans

In [40]:
# Read the graph from the file
edges = []
with open("out.dimacs10-polbooks.txt", "r") as file:
    for line in file:
        edge = tuple(map(int, line.strip().split()))
        edges.append(edge)

# Find the number of nodes in the graph
num_nodes = max(max(edge) for edge in edges)

# Create an adjacency matrix
adjacency_matrix = np.zeros((num_nodes, num_nodes))
for edge in edges:
    adjacency_matrix[edge[0] - 1, edge[1] - 1] = 1
    adjacency_matrix[edge[1] - 1, edge[0] - 1] = 1

# Display the adjacency matrix
print("Adjacency Matrix:")
print(adjacency_matrix)

Adjacency Matrix:
[[0. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [41]:
# Compute the degree matrix
degree_matrix = np.diag(np.sum(adjacency_matrix, axis=1))

# Compute the Laplacian matrix
laplacian_matrix = degree_matrix - adjacency_matrix

# Display the Laplacian matrix
print("\nLaplacian Matrix:")
print(laplacian_matrix)


Laplacian Matrix:
[[ 6. -1. -1. ...  0.  0.  0.]
 [-1.  4.  0. ...  0.  0.  0.]
 [-1.  0.  4. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  3.  0.  0.]
 [ 0.  0.  0. ...  0.  7.  0.]
 [ 0.  0.  0. ...  0.  0.  5.]]


In [42]:
# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eigh(laplacian_matrix)

# Display eigenvalues and eigenvectors
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[6.70801621e-17 3.23607315e-01 7.64480671e-01 1.39014114e+00
 1.60287332e+00 1.81029903e+00 1.89250401e+00 2.10044318e+00
 2.17853718e+00 2.63084779e+00 2.76657841e+00 2.84081648e+00
 2.88371446e+00 2.88653383e+00 2.96865938e+00 3.09918475e+00
 3.27347119e+00 3.30476486e+00 3.33892723e+00 3.62132877e+00
 3.63192871e+00 3.71872054e+00 3.80634416e+00 3.92725157e+00
 4.02083438e+00 4.07322788e+00 4.13854286e+00 4.22682751e+00
 4.24952030e+00 4.28173596e+00 4.34902004e+00 4.39149924e+00
 4.45848707e+00 4.73116025e+00 4.73743434e+00 4.80556197e+00
 5.02819180e+00 5.05252730e+00 5.08078438e+00 5.17158993e+00
 5.29282448e+00 5.40607197e+00 5.45701783e+00 5.62478170e+00
 5.72548679e+00 5.76157025e+00 5.81362220e+00 6.08780252e+00
 6.34755438e+00 6.40748397e+00 6.45403899e+00 6.50759802e+00
 6.57332155e+00 6.74268904e+00 6.80542200e+00 6.81254881e+00
 6.87312163e+00 7.02302231e+00 7.04283659e+00 7.15655511e+00
 7.45613397e+00 7.52065405e+00 7.61646007e+00 7.79073035e+00
 7.8406300

In [43]:
# Create a dictionary to store node representations
node_representations = {}

# For each node, use the corresponding row from the eigenvector matrix
for i in range(num_nodes):
    node_representations[i + 1] = eigenvectors[:, i]

# Display node representations
print("\nNode Representations:")
for node, representation in node_representations.items():
    print(f"Node {node}: {representation}")


Node Representations:
Node 1: [0.09759001 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001
 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001
 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001
 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001
 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001
 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001
 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001
 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001
 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001
 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001
 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001
 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001
 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001
 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001 0.09759001
 0.09759001 0.09759001 0.097590

In [44]:
# Function to compute the Min-Cut
def compute_min_cut(adjacency_matrix, labels):
    cut = 0
    for i in range(adjacency_matrix.shape[0]):
        for j in range(i + 1, adjacency_matrix.shape[0]):
            if labels[i] != labels[j] and adjacency_matrix[i, j] == 1:
                cut += 1
    return cut

# Function to compute Modularity
def compute_modularity(adjacency_matrix, labels):
    num_nodes = adjacency_matrix.shape[0]
    total_edges = np.sum(adjacency_matrix) / 2
    degrees = np.sum(adjacency_matrix, axis=1)

    modularity = 0
    for i in range(num_nodes):
        for j in range(num_nodes):
            modularity += (adjacency_matrix[i, j] - (degrees[i] * degrees[j]) / (2 * total_edges)) \
                          * int(labels[i] == labels[j])

    modularity /= (2 * total_edges)
    return modularity

In [48]:
# Range of k values to try
k_values = range(2, 11)

# Dictionary to store results for each k
results = {'k': [], 'Min-Cut': [], 'Modularity': []}

# Iterate over k values
for k in k_values:
    # Perform k-means clustering
    kmeans = KMeans(n_clusters=k, random_state=42)
    labels = kmeans.fit_predict(eigenvectors)

    # Compute Min-Cut and Modularity
    min_cut = compute_min_cut(adjacency_matrix, labels)
    modularity = compute_modularity(adjacency_matrix, labels)

    # Store results
    results['k'].append(k)
    results['Min-Cut'].append(min_cut)
    results['Modularity'].append(modularity)

# Display results
print("\nResults:")
print("k   Min-Cut   Modularity")
for i in range(len(k_values)):
    print(f"{results['k'][i]:2d}  {results['Min-Cut'][i]:7d}  {results['Modularity'][i]:.4f}")

# Find the index with the maximum Modularity
best_modularity_index = np.argmax(results['Modularity'])

# Find the index with the minimum Min-Cut for the cases where Modularity is maximized
best_min_cut_index = np.argmin([results['Min-Cut'][i] for i in range(best_modularity_index, len(k_values))])

# Display the best values
best_k_modularity = results['k'][best_modularity_index]
best_k_min_cut = results['k'][best_min_cut_index + best_modularity_index]

print("\nBest Values:")
print(f"Best k for Modularity: {best_k_modularity}")
print(f"Best k for Min-Cut (with best Modularity): {best_k_min_cut}")

E:\University\M.Sc\Terms\Term2\Applied Machine Learning\Project\Codes\1\venv\lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
E:\University\M.Sc\Terms\Term2\Applied Machine Learning\Project\Codes\1\venv\lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
E:\University\M.Sc\Terms\Term2\Applied Machine Learning\Project\Codes\1\venv\lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
E:\University\M.Sc\


Results:
k   Min-Cut   Modularity
 2       61  0.0021
 3       66  0.0038
 4      222  0.0427
 5      128  -0.0093
 6      282  -0.0033
 7      205  0.0241
 8      146  0.0135
 9       79  0.0027
10      177  0.0114

Best Values:
Best k for Modularity: 4
Best k for Min-Cut (with best Modularity): 9
